--- # AWS Module example on  VPC facts
- hosts: localhost
  gather_facts: no
  vars_files:
    - keys.yml

  tasks:
    - name: Get VPC Facts
      ec2_vpc_net_facts:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        filters:
          "tag:Name": NewVPC
      register: vpc_facts
    - debug:
        var: item.cidr_block
      loop: "{{ vpc_facts.vpcs }}"
