--- #Stopping instance based on the tag Name: Demo
- hosts: localhost
  gather_facts: no
  vars_files:
    - keys.yml
  tasks:
    - name: Change Instance state by tag
      ec2: 
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        state: stopped
        instance_tags:
          Name: Demo 