--- # Launching EC2 instance in AWS environment
- hosts: localhost
  gather_facts: no
  vars_files:
    - keys.yml
  tasks:
    - name: Provision instance
      ec2: 
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        instance_type: t2.micro
        key_name:  aws-ansible-key  # from aws ec2 console
        image: ami-0947d2ba12ee1ff75   # from aws ec2 console #amazon-linux-2
        assign_public_ip: yes
        vpc_subnet_id: subnet-09b78fa9b2aad6535  #from aws VPC console # can be pulled from ansible facts
        group: default #demoSG # from aws console
        wait: true
        exact_count: 2 # how many do you want to exist when the book is done running
        count_tag:
          Name: Demo
        instance_tags: # assigning tags to ec2
          Name: Demo
      register: ec2 # register the output of ec2 module
    - debug:
        var: ec2
      

    - name: add host to inventory
      add_host:
        hostname: '{{ item.public_ip }}'
        groupname: demogroup
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
        ansible_ssh_private_key_file: /home/ansible/aws-ansible-key.pem   ####
      loop: '{{ ec2.instances }}'

- hosts: demogroup
  gather_facts: no # doesn't wait long enough and errors out because of that
  remote_user: ec2-user
  tasks:
    - name: wait for SSH 
      wait_for_connection:
        delay: 5
        timeout: 90

    - name: check host status 
      ping:

