--- # AWS AMI example
- hosts: localhost
  gather_facts: no
  vars_files:
    - keys.yml
  tasks:
    - name: Create new AMI
      ec2_ami: 
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        instance_id: i-099c4d26fcc17c3ac #provide instance id here 
        name: MyNewAMI # if name already exist it will error out 
        #wait: yes  #handy in case we want to do something with it right away.
        state: present

    - name: Delete existing AMI
      ec2_ami: 
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        image_id: ami-097c52fa032a4f4f8
        state: absent
      register: ami_deleted

    - name: Copy AMI to another region
      ec2_ami_copy: 
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        # ec2_region: "{{ AWS_REGION }}"
        source_region: "{{ AWS_REGION }}"
        region: us-west-2 #into which region we copy to
        source_image_id: ami-06d0f14eb5f53da1f  #Image id that will be copied
        name: MyNewAMI_inNew_region # if name already exist it will error out 
        wait: no  #
      register: ec2_ami_info

    - name: Check out gathered facts
      debug:
        var: ec2_ami_info.name

