--- # AWS ec2_vol Example
- hosts: localhost
  gather_facts: no
  vars_files:
    - keys.yml
  tasks:
    - name: Attach Volume
      ec2_vol: 
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        instance: i-0558e1a38673dd91b
        id: vol-03b2af41ff5b22a99 #1 Gb vol created earlier
        delete_on_termination: yes
      register: vol_info
    - debug:
        var: vol_info